version: "3.9"  # optional since v1.27.0
services:
  university:
    build: .
    container_name: university-orm
    restart: unless-stopped
    networks:
      - app-networks
  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
    ports:
      - "5432:5432"

networks:
  app-networks:
    driver: bridge