import random

def fake_subject():
    return random.choice(subjects)

subjects = [
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Engineering",
    "Literature",
    "History",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Business Administration",
    "Marketing",
    "Accounting",
    "Law",
    "Medicine",
    "Nursing",
    "Pharmacy",
    "Architecture",
    "Art History",
    "Music Theory",
    "Theatre Studies",
    "Environmental Science",
    "Geology",
    "Geography",
    "Astronomy",
    "Linguistics",
    "Spanish",
    "German",
    "Chinese",
    "Ukrainian",
    "Education",
    "Communication Studies",
    "Journalism",
    "Film Studies",
    "Cultural Studies",
    "Gender Studies",
    "Religious Studies",
    "Physical Education",
    "Agricultural Sciences",
    "Veterinary Medicine"
]