import random

def fake_subject():
    return random.choice(subjects)

subjects = [
    "Mathematics",
    "Physics",
    "Chemistry",
    "Biology",
    "Computer Science",
    "Engineering",
    "Literature",
    "History",
    "Philosophy",
    "Political Science",
    "Psychology",
    "Sociology",
    "Anthropology",
    "Economics",
    "Business Administration",
    "Marketing",
    "Accounting",
    "Law",
    "Medicine",
    "Nursing",
    "Pharmacy",
    "Architecture",
    "Art History",
    "Music Theory",
    "Theatre Studies",
    "Environmental Science",
    "Geology",
    "Geography",
    "Astronomy",
    "Linguistics",
    "Spanish",
    "German",
    "Chinese",
    "Ukrainian",
    "Education",
    "Communication Studies",
    "Journalism",
    "Film Studies",
    "Cultural Studies",
    "Gender Studies",
    "Religious Studies",
    "Physical Education",
    "Agricultural Sciences",
    "Veterinary Medicine"
]

def fake_group_name():
    return random.choice(group_list)

group_list = [
    "101A",
    "101B",
    "102A",
    "102B",
    "103A",
    "103B",
    "104A",
    "104B",
    "105A",
    "105B",
    "106A",
    "106B",
    "107A",
    "107B",
    "108A",
    "108B",
    "109A",
    "109B",
    "110A",
    "110B",
    "111A",
    "111B",
    "112A",
    "112B",
    "113A", 
    "113B",
    "114A",
    "114B",
    "115A",
    "115B",
    "116A",
    "116B",
    "117A",
    "117B",
    "118A",
    "118B",
    "119A",
    "119B",
    "120A",
    "120B",
    "121A",
    "121B",
    "122A",
    "122B",
    "123A"
]